### PR TITLE
fix: changed Exception typehint to Throwable as when a TypeError occurs.

### PR DESCRIPTION
**Pull request by kiettran**
This pull request should fix the following error that occurs when you've given the wrong parameter type.

```shell
Argument 1 passed to Nijens\OpenapiBundle\Service\ExceptionJsonResponseBuilder::build() must be an instance of Exception, instance of TypeError given, called in /var/www/vendor/nijens/openapi-bundle/src/EventListener/JsonResponseExceptionSubscriber.php on line 78
```

The message of the error.
```shell
"Argument 7 passed to XXX::__construct() must implement interface DateTimeInterface, array given, called in /var/www/src/XXX.php on line 67"
```

### CODE REVIEW

**Comment by niels-nijens** [comment]
The way this is changed is a backwards compatibility break on the `ExceptionJsonResponseBuilderInterface`. I would rather find a different solution to this without changing the interface.

**Comment by kiettran** [comment]
> The way this is changed is a backwards compatibility break on the `ExceptionJsonResponseBuilderInterface`. I would rather find a different solution to this without changing the interface.

Why is this a backwards compatibility break? With this change It is going to support both types of error, a TypeError or an Exception. They both implement the Throwable Interface. Unless you do not want to support the TypeErrors that can be given when the developer defines wrong types or arguments.. Then I'd like to suggest to suppress these types of errors.

**Comment by niels-nijens** [comment]
> Why is this a backwards compatibility break?

You will get a fatal error when you've created a custom `ExceptionJsonResponseBuilder` with Exception as argument. See: https://3v4l.org/nG6ET

> Unless you do not want to support the TypeErrors that can be given when the developer defines wrong types or arguments.

It's not wanting to support it. I'm just not willing to introduce a backwards compatibility break for it.

A (temporary) solution for example could be converting a `Throwable` to an `Exception` within the event subscriber.

**Comment by niels-nijens** [comment]
Thank you for your help in fixing this issue. It has been merged in #48.

**Pull request closed without merging**
